### PR TITLE
Fixes warnings during REPL startup while using custom SYSIMG's

### PR DESCRIPTION
**Pull request by bmharsha**
We encounter following warning during Julia REPL startup if we include DistributionsAD in the default SYSIMG, this PR fixes that issue

```
┌ Warning: Error requiring `ForwardDiff` from `DistributionsAD`
│   exception =
│    LoadError: SystemError: opening file "/home/bmharsha/.julia/packages/DistributionsAD/pj8zf/src/reversediffx.jl": No such file or directory
│    Stacktrace:
│      [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
│        @ Base ./error.jl:168
│      [2] #systemerror#62
│        @ ./error.jl:167 [inlined]
│      [3] systemerror
│        @ ./error.jl:167 [inlined]
│      [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
│        @ Base ./iostream.jl:293
│      [5] open
│        @ ./iostream.jl:282 [inlined]
│      [6] open(f::Base.var"#326#327"{String}, args::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Base ./io.jl:328
│      [7] open
│        @ ./io.jl:328 [inlined]
│      [8] read
│        @ ./io.jl:434 [inlined]
│      [9] _include(mapexpr::Function, mod::Module, _path::String)
│        @ Base ./loading.jl:1166
│     [10] include(mod::Module, _path::String)
│        @ Base ./Base.jl:386
│     [11] include(x::String)
│        @ DistributionsAD.ReverseDiffX ./reversediff.jl:1
│     [12] top-level scope
│        @ reversediff.jl:55
│     [13] eval
│        @ ./boot.jl:360 [inlined]
│     [14] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base ./loading.jl:1116
│     [15] include_string(m::Module, txt::String, fname::String)
│        @ Base ./loading.jl:1126
│     [16] macro expansion
│        @ ~/.julia/packages/Requires/7Ncym/src/Requires.jl:42 [inlined]
│     [17] top-level scope
│        @ ~/.julia/packages/DistributionsAD/pj8zf/src/DistributionsAD.jl:74
│     [18] eval
│        @ ./boot.jl:360 [inlined]
│     [19] eval
│        @ ~/.julia/packages/DistributionsAD/pj8zf/src/DistributionsAD.jl:1 [inlined]
│     [20] (::DistributionsAD.var"#331#334")()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/require.jl:99
│     [21] err(f::Any, listener::Module, modname::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:47
│     [22] (::DistributionsAD.var"#330#333")()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/require.jl:98
│     [23] withpath(f::Any, path::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:37
│     [24] (::DistributionsAD.var"#329#332")()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/require.jl:97
│     [25] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:20
│     [26] macro expansion
│        @ ~/.julia/packages/Requires/7Ncym/src/require.jl:95 [inlined]
│     [27] top-level scope
│        @ ~/.julia/packages/DistributionsAD/pj8zf/src/DistributionsAD.jl:73
│     [28] eval
│        @ ./boot.jl:360 [inlined]
│     [29] eval
│        @ ~/.julia/packages/DistributionsAD/pj8zf/src/DistributionsAD.jl:1 [inlined]
│     [30] (::DistributionsAD.var"#307#320")()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/require.jl:99
│     [31] err(f::Any, listener::Module, modname::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:47
│     [32] (::DistributionsAD.var"#306#319")()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/require.jl:98
│     [33] withpath(f::Any, path::String)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:37
│     [34] (::DistributionsAD.var"#305#318")()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/require.jl:97
│     [35] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:20
│     [36] macro expansion
│        @ ~/.julia/packages/Requires/7Ncym/src/require.jl:95 [inlined]
│     [37] macro expansion
│        @ ~/.julia/packages/DistributionsAD/pj8zf/src/DistributionsAD.jl:70 [inlined]
│     [38] (::DistributionsAD.var"#301#314")()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/init.jl:11
│     [39] __init__()
│        @ DistributionsAD ~/.julia/packages/Requires/7Ncym/src/init.jl:18
│    in expression starting at reversediff.jl:1
└ @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:49
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.2 (2021-07-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

[?2004h
[0Kjulia>
[7C
[7C
[?2004l
```

In this PR, we move the contents of `reversediffx.jl` into `reversediff.jl` because the `Requires.jl` way of bundling the source code inside the precompiled package only looks one level deep, so the usage of `include` function inside `reversediff.jl` was creating aforementioned issue after `TuringLang/DistributionsAD.jl` was compiled into a SYSIMG.

### CODE REVIEW

**Review by yebai — APPROVED** [review]

**Comment by yebai** [comment]
thanks, @bmharsha - this looks good, ready to merge once CI passes!

**Comment by yebai** [comment]
@bmharsha can you also bump the version, so we can make a new release after merging?

**Comment by bmharsha** [comment]
>@bmharsha can you also bump the version, so we can make a new release after merging?

Sure, I just updated the version number to v0.6.29 in Project.toml

**Comment by yebai** [comment]
Some numerical tests are failing, which is a bit odd given that this PR does not introduce any functionality changes. These errors might be caused by upper stream changes, e.g. in `Distributions.jl`.

**Comment by devmotion** [comment]
Same comment as in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/350#issuecomment-894129714: It shouldn't be necessary to use `Requires.@include` since Requires already replaces all occurrences of `include` with `@include`.

**Comment by bmharsha** [comment]
>It shouldn't be necessary to use Requires.@include since Requires already replaces all occurrences of include with @include.

The Requires.jl way of bundling the source code inside the precompiled package only looks one level deep. So, the major takeaway from this PR is moving the contents of `src/reversediffx.jl` to `src/reversediff.jl`, this is what fixes the warnings. Replacing `include` with `Requires.@include` was just done to be on the safer side.

**Comment by devmotion** [comment]
> Replacing `include` with `Requires.@include` was just done to be on the safer side.

Could these changes be reverted?

**Comment by bmharsha** [comment]
>Could these changes be reverted?

I reverted all the occurrences of `Requires.@include` to `include`

**Comment by yebai** [comment]
@bmharsha Looks good - before we merge this PR, could you take a look at why some tests are failing and see whether we can fix them?

**Comment by yebai** [comment]
It seems the tests of `arraydist` and `filldist` is broken for the `BetaPrime` distribution. The `BetaPrime` distribution is recently updated in [this](https://github.com/JuliaStats/Distributions.jl/pull/1348/files#diff-db7523a6e1e76d9adad4876d2f6a042b3996e0afa1ede07e87469d3335197fb6) Distributions PR.

@devmotion  I can't find any obvious reason why we got errors for `BetaPrime`. Any idea?

**Comment by devmotion** [comment]
I noticed that it is caused by `BetaPrime` and I also checked if I messed up the `logpdf` implementation. However, I didn't notice any bugs in the Distributions PR related to `logpdf(::BetaPrime, ::Real)` and did not perform any more extensive debugging (teaching in the SMC course takes most of my time this week). My hypothesis would be that it is caused by `xlogy` which was introduced in the PR.

**Comment by yebai** [comment]
Let's merge this PR first since the broken test seems not related to the changes introduced here. I created an issue for the broken `BetaPrime` distribution.

**Pull request merged**
