### PR TITLE
Actual fix for LazyArrays extension

### PR DESCRIPTION
**Pull request by torfjelde**
_Now_ it should be working.

### CODE REVIEW

**Comment by torfjelde** [comment]
I will say, all these broken tests (that are unrelated to this PR) makes it very difficult to tell whether the PR introduces any bugs :confused:

**Comment by devmotion** [comment]
Maybe we should just upper bound the FillArrays compat of all existing and future releases until we know what in the recent FillArrays release broke it.

The PR seems fine but can we extend our tests for the extension? Seems the ones in #246 were not sufficient.

**Comment by torfjelde** [comment]
I'm very confused as to what's going on the tests of #246 though. If you look at the logs for some of the tests, e.g. https://github.com/TuringLang/DistributionsAD.jl/actions/runs/5230268767/jobs/9443723459, you can see that it's indeed erroring on that important (just warning in the case of Revise.jl). But then on some tests it's still passing https://github.com/TuringLang/DistributionsAD.jl/actions/runs/5237692580/jobs/9456041448?pr=247.

**Comment by devmotion** [comment]
Ah, I had missed that some tests had failed due to these bugs. But yeah, strange that it doesn't fail every time.

**Comment by torfjelde** [comment]
> Ah, I had missed that some tests had failed due to these bugs.

Same; that's what trigger my comment about the currently failing tests makes it a bit harder to see what's going wrong :sweat_smile: 

> Maybe we should just upper bound the FillArrays compat of all existing and future releases until we know what in the recent FillArrays release broke it.

Do we have any idea if this will have downstream consequences? :Confused

**Comment by torfjelde** [comment]
But can we just get this merged? It's holding up quite a few PRs? :confused: I feel like upper-bounding FillArrays is a separate topic anyway.

**Comment by torfjelde** [comment]
This is the same as before with our TRacker support being broken, which was the case prior to this PR too (@devmotion is saying it's because of some FillArrays stuff, hence why he suggested we might want to upper bound FIllArryas for now)

**Pull request merged**
