### PR TITLE
Fix custom adjoint of `simplex_logpdf`

### PR DESCRIPTION
**Pull request by devmotion**
Fixes https://github.com/TuringLang/DistributionsAD.jl/issues/86.

(BTW I can't stand these testing times, I'll copy the fixes from Bijectors to DistributionsAD.)

### CODE REVIEW

**Comment by devmotion** [comment]
I don't know why Zyogte tests failed on macOS - there's no log available, not even in the log archive. Dirichlet tests on linux passed, according to the logs.

**Comment by torfjelde** [comment]
On my screen they're still running?

**Comment by devmotion** [comment]
Hmm maybe I restarted them accidentally? I rechecked the logs that I downloaded, and they are for this PR and from today...

**Comment by torfjelde** [comment]
Seems good to go?

**Comment by devmotion** [comment]
The modified tests passed as well in https://github.com/TuringLang/DistributionsAD.jl/pull/88.

**Comment by devmotion** [comment]
I guess it's fine if I make a new bugfix release? The only change from the previous release would be this fix.

**Comment by torfjelde** [comment]
I'd say so, but I'm not the "main-maintainer" of DistributionsAD, soooo. @mohamed82008 mby?

**Pull request merged**
