### PR TITLE
Few AD fixes and improvements

### PR DESCRIPTION
**Pull request by mohamed82008**
In this PR:
1. Some binary array functions are defined for `Tracker.TrackedArray` and `Array{<:TrackedReal}` to work around https://github.com/FluxML/Tracker.jl/issues/4.
2. An `MvCategorical` distribution is defined to address #62 .
3. Some RD broadcasting issues for discrete univariate distributions are fixed and other custom adjoints are added.

### CODE REVIEW

**Comment by mohamed82008** [comment]
Tests seem to fail because of a Zygote issue. I will investigate.

**Comment by mohamed82008** [comment]
The latest Zygote errors on Julia 1.0.

**Comment by mohamed82008** [comment]
https://github.com/FluxML/Zygote.jl/pull/628

**Comment by cossio** [comment]
Is there something here that can be used as a test for https://github.com/FluxML/Zygote.jl/pull/628?

**Comment by mohamed82008** [comment]
>Is there something here that can be used as a test for FluxML/Zygote.jl#628?

`using Zygote` ;)

**Comment by cossio** [comment]
Yeah sorry I missed that the issue was just on Julia 1.0!

**Pull request merged**
