### PR TITLE
[WIP] Update to Distributions 0.24.12

### PR DESCRIPTION
**Pull request by devmotion**
This PR updates DistributionsAD to Distributions >= 0.24.12. The latest version of Distributions contains many things that previously had to be fixed in DistributionsAD and therefore allows us to remove a large part of DistributionsAD. E.g., it supports automatically
- Dirichlet distributons with general parameter vectors (https://github.com/JuliaStats/Distributions.jl/pull/1243)
- `logpdf` for matrices and arrays of samples (https://github.com/JuliaStats/Distributions.jl/pull/1263)
- construction of more general `DiscreteNonParametric` distributions (https://github.com/JuliaStats/Distributions.jl/pull/1184)
- a faster more accurate pdf of the Poisson binomial distribution that does not use FFTs (https://github.com/JuliaStats/Distributions.jl/pull/1198)

This allows us e.g. to remove the overly optimistic `logpdf` pullbacks and fixes https://github.com/TuringLang/DistributionsAD.jl/issues/121 since Distributions now contains the fix suggested in https://github.com/TuringLang/DistributionsAD.jl/issues/121#issuecomment-709957943.

### CODE REVIEW

**Comment by devmotion** [comment]
Seems that `eltype(::Type{<:TrackedArray}) isa TrackedReal` causes problems with `Dirichlet` and the `Dirichlet` tests for ReverseDiff yield the same errors as in https://github.com/TuringLang/DistributionsAD.jl/pull/146. Might be better to remove the `Dirichlet` changes from this PR.

**Comment by devmotion** [comment]
The ReverseDiff adjoints for `simplex_logpdf` are wrong, but it seems that they are not responsible for the ReverseDiff test failures.

**Review by yebai — APPROVED** [review]
Thanks, @devmotion - it looks good to me!

**Comment by yebai** [comment]
Ps, it seems the test for ReverseDiff is broken: https://github.com/TuringLang/DistributionsAD.jl/pull/150/checks?check_run_id=1783614538#step:5:231

**Comment by devmotion** [comment]
I assume the test failures are (at least partly) fixed by https://github.com/TuringLang/DistributionsAD.jl/pull/151.

**Comment by yebai** [comment]
@devmotion Just a gentle reminder - happy to merge this once the merge conflicts are resolved and CI passing.

**Comment by devmotion** [comment]
I'll close this since it is partly covered by https://github.com/TuringLang/DistributionsAD.jl/pull/198 and it is probably cleaner to make a new PR for the remaining changes in this PR.

**Pull request closed without merging**
