### PR TITLE
Remove `MvDiscreteNonParametric`

### PR DESCRIPTION
**Pull request by devmotion**
A quite drastic fix for https://github.com/TuringLang/DistributionsAD.jl/issues/168 and https://github.com/TuringLang/DistributionsAD.jl/issues/167.

The implementation is quite outdated, many upstream changes were not propagated, the log pdf is wrong, and AD seems to work nevertheless. I believe possible performance regressions should be fixed in a more targeted way and/or upstream.

### CODE REVIEW

**Comment by mohamed82008** [comment]
I am not in favor of this. If it's wrong or out-dated, it should be fixed. If it should be upstreamed, then it should only be removed after the upstreaming is completed.

**Comment by devmotion** [comment]
What is the reason for the custom implementation in DistributionsAD? If it was SubArray support or AD, both were fixed by upstream changes.

**Comment by devmotion** [comment]
The current state is pretty bad since it is unclear why the implementation exists at all and almost everything is copied from a now outdated version of Distributions. This will be difficult to maintain in the future as well.

**Comment by mohamed82008** [comment]
> What is the reason for the custom implementation in DistributionsAD?

Performance improvement for the vector case for AD.

**Comment by devmotion** [comment]
Yeah but these performance improvements were achieved with an incorrect log pdf 😄

**Comment by mohamed82008** [comment]
>Yeah but these performance improvements were achieved with an incorrect log pdf 😄

Possibly, but the solution is to fix it and check again.

**Pull request merged**
